const $ = (id) => document.getElementById(id);
const els = { file:$('fileInput'), drop:$('dropZone'), choose:$('chooseButton'), source:$('sourceImage'), fileName:$('fileName'), clear:$('clearSource'), canvas:$('outputCanvas'), empty:$('emptyPreview'), pixel:$('pixelSize'), pixelOut:$('pixelOutput'), size:$('sizeReadout'), palette:$('paletteInput'), apply:$('applyPalette'), gray:$('grayscale'), brightness:$('brightness'), contrast:$('contrast'), saturation:$('saturation'), grid:$('gridToggle'), compare:$('compareToggle'), zoom:$('zoomRange'), zoomOut:$('zoomOutput'), scale:$('exportScale'), download:$('downloadButton'), reset:$('resetButton') };
const presets = [
  {name:'Garden', colors:['#2d1b45','#6b3fa0','#f1c96b','#f8f0d8']}, {name:'Forest', colors:['#152d23','#436b42','#91a857','#f0db9a']},
  {name:'Sunset', colors:['#331b3d','#8b3e5d','#e56b4f','#ffd166']}, {name:'Ocean', colors:['#172a45','#246a8a','#62b6cb','#d7f0f7']},
  {name:'Game Boy', colors:['#0f380f','#306230','#8bac0f','#9bbc0f']}
];
let sourceBitmap = null, sourceName = '', activePreset = 0;
function drawPresetButtons() { const host = $('palettePresets'); host.replaceChildren(); presets.forEach((preset,index) => { const button = document.createElement('button'); button.className = 'preset' + (index === activePreset ? ' active':''); button.title = preset.name; button.setAttribute('aria-label', preset.name + ' palette'); ['a','b','c','d'].forEach((letter,i)=>button.style.setProperty('--'+letter,preset.colors[i])); button.onclick = () => { activePreset=index; els.palette.value=preset.colors.join(', '); drawPresetButtons(); render(); }; host.append(button); }); }
function paletteColors() { return els.palette.value.split(',').map(x=>x.trim()).filter(x=>/^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(x)).slice(0,16); }
function updateLabels() { const px=+els.pixel.value; els.pixelOut.value=px; els.size.textContent=`${px} × ${px} PX`; ['brightness','contrast','saturation'].forEach(key => $(key+'Value').value = els[key].value); els.zoomOut.value=`${Math.round(+els.zoom.value*100)}%`; els.canvas.style.transform=`scale(${els.zoom.value})`; }
function filterColor(r,g,b) { if (els.gray.checked) { const l=.299*r+.587*g+.114*b; r=g=b=l; } const brightness=+els.brightness.value*2.55; r+=brightness;g+=brightness;b+=brightness; const contrast=(+els.contrast.value+100)/100; r=(r-128)*contrast+128;g=(g-128)*contrast+128;b=(b-128)*contrast+128; const saturation=(+els.saturation.value+100)/100; const l=.299*r+.587*g+.114*b; return [l+(r-l)*saturation,l+(g-l)*saturation,l+(b-l)*saturation].map(v=>Math.max(0,Math.min(255,v))); }
function nearest(color, colors) { let best=colors[0], distance=Infinity; colors.forEach(hex=>{ const n=hex.slice(1).length===3 ? hex.slice(1).split('').map(x=>x+x).join('') : hex.slice(1); const c=[parseInt(n.slice(0,2),16),parseInt(n.slice(2,4),16),parseInt(n.slice(4,6),16)]; const d=(color[0]-c[0])**2+(color[1]-c[1])**2+(color[2]-c[2])**2; if(d<distance){distance=d;best=c;} }); return best; }
function render() { updateLabels(); if (!sourceBitmap) return; const pixels=+els.pixel.value, small=document.createElement('canvas'), sctx=small.getContext('2d',{willReadFrequently:true}); small.width=small.height=pixels; sctx.imageSmoothingEnabled=true; const scale=Math.max(pixels/sourceBitmap.width,pixels/sourceBitmap.height); const w=sourceBitmap.width*scale,h=sourceBitmap.height*scale; sctx.drawImage(sourceBitmap,(pixels-w)/2,(pixels-h)/2,w,h); const ctx=els.canvas.getContext('2d'); els.canvas.width=els.canvas.height=512; ctx.imageSmoothingEnabled=false; ctx.clearRect(0,0,512,512); if (els.compare.checked) { ctx.drawImage(sourceBitmap,(512-w*512/pixels)/2,(512-h*512/pixels)/2,w*512/pixels,h*512/pixels); els.empty.hidden=true; els.download.disabled=false; return; } const image=sctx.getImageData(0,0,pixels,pixels), colors=paletteColors(); for(let i=0;i<image.data.length;i+=4){if(image.data[i+3]<20)continue; let c=filterColor(image.data[i],image.data[i+1],image.data[i+2]); if(colors.length)c=nearest(c,colors); image.data[i]=c[0];image.data[i+1]=c[1];image.data[i+2]=c[2];} sctx.putImageData(image,0,0); ctx.drawImage(small,0,0,512,512); if(els.grid.checked && pixels<=32){ctx.strokeStyle='rgba(45,27,69,.24)';ctx.lineWidth=1; const step=512/pixels;for(let i=0;i<=pixels;i++){ctx.beginPath();ctx.moveTo(i*step,0);ctx.lineTo(i*step,512);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*step);ctx.lineTo(512,i*step);ctx.stroke();}} els.empty.hidden=true; els.download.disabled=false; }
function loadFile(file) { if(!file || !file.type.startsWith('image/')) return; const url=URL.createObjectURL(file); const image=new Image(); image.onload=()=>{sourceBitmap=image;sourceName=file.name;els.source.src=url;els.source.hidden=false;els.fileName.textContent=file.name.toUpperCase();els.clear.disabled=false;render();}; image.src=url; }
function clearSource(){ sourceBitmap=null;els.source.hidden=true;els.source.removeAttribute('src');els.file.value='';els.fileName.textContent='NO IMAGE SELECTED';els.clear.disabled=true;els.download.disabled=true;els.empty.hidden=false;els.canvas.getContext('2d').clearRect(0,0,els.canvas.width,els.canvas.height); }
els.choose.onclick=()=>els.file.click();els.file.onchange=e=>loadFile(e.target.files[0]);els.clear.onclick=clearSource;
['dragenter','dragover'].forEach(event=>els.drop.addEventListener(event,e=>{e.preventDefault();els.drop.classList.add('dragging')}));['dragleave','drop'].forEach(event=>els.drop.addEventListener(event,e=>{e.preventDefault();els.drop.classList.remove('dragging')}));els.drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));els.drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();els.file.click();}});
[els.pixel,els.gray,els.brightness,els.contrast,els.saturation,els.grid,els.compare,els.zoom].forEach(control=>control.addEventListener('input',render));els.apply.onclick=render;els.palette.addEventListener('change',render);
document.querySelectorAll('input[name=background]').forEach(el=>el.addEventListener('change',render));els.reset.onclick=()=>{els.pixel.value=16;els.palette.value=presets[0].colors.join(', ');activePreset=0;els.gray.checked=false;els.brightness.value=0;els.contrast.value=0;els.saturation.value=0;els.grid.checked=true;els.compare.checked=false;els.zoom.value=1;document.querySelector('[name=background][value=transparent]').checked=true;drawPresetButtons();render();};
els.download.onclick=()=>{if(!sourceBitmap)return; const scale=+els.scale.value, final=document.createElement('canvas'),ctx=final.getContext('2d');final.width=final.height=512*scale;if(document.querySelector('[name=background]:checked').value==='cream'){ctx.fillStyle='#f8f0dd';ctx.fillRect(0,0,final.width,final.height);}ctx.imageSmoothingEnabled=false;ctx.drawImage(els.canvas,0,0,final.width,final.height);const a=document.createElement('a');a.download=(sourceName.replace(/\.[^.]+$/,'')||'pixel-art')+'-pixel.png';a.href=final.toDataURL('image/png');a.click();};
drawPresetButtons();updateLabels();
