const $ = (id) => document.getElementById(id);
const els = { file:$('fileInput'), drop:$('dropZone'), choose:$('chooseButton'), source:$('sourceImage'), fileName:$('fileName'), clear:$('clearSource'), canvas:$('outputCanvas'), empty:$('emptyPreview'), pixel:$('pixelSize'), pixelOut:$('pixelOutput'), size:$('sizeReadout'), palette:$('paletteInput'), apply:$('applyPalette'), paletteMore:$('paletteMore'), paletteMorePanel:$('paletteMorePanel'), autoPalette:$('autoPalette'), colorCount:$('colorCount'), dither:$('dither'), paletteNote:$('paletteNote'), gray:$('grayscale'), brightness:$('brightness'), contrast:$('contrast'), saturation:$('saturation'), grid:$('gridToggle'), compare:$('compareToggle'), zoom:$('zoomRange'), zoomOut:$('zoomOutput'), scale:$('exportScale'), download:$('downloadButton'), reset:$('resetButton') };
const presets = [
  {name:'Original — no palette', colors:[], original:true}, {name:'Garden', colors:['#2d1b45','#6b3fa0','#f1c96b','#f8f0d8']}, {name:'Forest', colors:['#152d23','#436b42','#91a857','#f0db9a']},
  {name:'Sunset', colors:['#331b3d','#8b3e5d','#e56b4f','#ffd166']}, {name:'Ocean', colors:['#172a45','#246a8a','#62b6cb','#d7f0f7']},
  {name:'Game Boy', colors:['#0f380f','#306230','#8bac0f','#9bbc0f']}
];
let sourceBitmap = null, sourceName = '', activePreset = 1;
function drawPresetButtons() { const host = $('palettePresets'); host.replaceChildren(); presets.forEach((preset,index) => { const button = document.createElement('button'); button.className = 'preset' + (preset.original ? ' original':'') + (index === activePreset ? ' active':''); button.title = preset.name; button.setAttribute('aria-label', preset.name); ['a','b','c','d'].forEach((letter,i)=>button.style.setProperty('--'+letter,preset.colors[i])); button.onclick = () => { activePreset=index; els.palette.value=preset.colors.join(', '); drawPresetButtons(); render(); }; host.append(button); }); }
function paletteColors() { return els.palette.value.split(',').map(x=>x.trim()).filter(x=>/^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(x)).slice(0,16); }
function rgbFromHex(hex) { const n=hex.slice(1).length===3 ? hex.slice(1).split('').map(x=>x+x).join('') : hex.slice(1); return [parseInt(n.slice(0,2),16),parseInt(n.slice(2,4),16),parseInt(n.slice(4,6),16)]; }
function hexFromRgb(color) { return '#'+color.map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join(''); }
function updateLabels() { const px=+els.pixel.value; els.pixelOut.value=px; els.size.textContent=`${px} × ${px} PX`; document.querySelectorAll('.pixel-presets button').forEach(button => button.classList.toggle('active', +button.dataset.size === px)); ['brightness','contrast','saturation'].forEach(key => $(key+'Value').value = els[key].value); els.zoomOut.value=`${Math.round(+els.zoom.value*100)}%`; els.canvas.style.transform=`scale(${els.zoom.value})`; }
function filterColor(r,g,b) { if (els.gray.checked) { const l=.299*r+.587*g+.114*b; r=g=b=l; } const brightness=+els.brightness.value*2.55; r+=brightness;g+=brightness;b+=brightness; const contrast=(+els.contrast.value+100)/100; r=(r-128)*contrast+128;g=(g-128)*contrast+128;b=(b-128)*contrast+128; const saturation=(+els.saturation.value+100)/100; const l=.299*r+.587*g+.114*b; return [l+(r-l)*saturation,l+(g-l)*saturation,l+(b-l)*saturation].map(v=>Math.max(0,Math.min(255,v))); }
function nearest(color, colors) { let best=rgbFromHex(colors[0]), distance=Infinity; colors.forEach(hex=>{ const c=rgbFromHex(hex); const d=(color[0]-c[0])**2+(color[1]-c[1])**2+(color[2]-c[2])**2; if(d<distance){distance=d;best=c;} }); return best; }
function spreadError(buffer, index, error, amount) { if (index < 0 || index >= buffer.length || buffer[index+3] < 20) return; buffer[index]+=error[0]*amount; buffer[index+1]+=error[1]*amount; buffer[index+2]+=error[2]*amount; }
function render() { updateLabels(); if (!sourceBitmap) return; const pixels=+els.pixel.value, small=document.createElement('canvas'), sctx=small.getContext('2d',{willReadFrequently:true}); small.width=small.height=pixels; sctx.imageSmoothingEnabled=true; const scale=Math.min(pixels/sourceBitmap.width,pixels/sourceBitmap.height), w=sourceBitmap.width*scale,h=sourceBitmap.height*scale; sctx.drawImage(sourceBitmap,(pixels-w)/2,(pixels-h)/2,w,h); const ctx=els.canvas.getContext('2d'); els.canvas.width=els.canvas.height=512; ctx.imageSmoothingEnabled=false; ctx.clearRect(0,0,512,512); if (els.compare.checked) { ctx.drawImage(sourceBitmap,(512-w*512/pixels)/2,(512-h*512/pixels)/2,w*512/pixels,h*512/pixels); els.empty.hidden=true; els.download.disabled=false; return; } const image=sctx.getImageData(0,0,pixels,pixels), colors=paletteColors(), working=new Float32Array(image.data.length); for(let i=0;i<image.data.length;i+=4){working[i+3]=image.data[i+3]; if(image.data[i+3]>=20){const c=filterColor(image.data[i],image.data[i+1],image.data[i+2]);working[i]=c[0];working[i+1]=c[1];working[i+2]=c[2];}} for(let y=0;y<pixels;y++){for(let x=0;x<pixels;x++){const i=(y*pixels+x)*4;if(working[i+3]<20)continue;const input=[working[i],working[i+1],working[i+2]], output=colors.length?nearest(input,colors):input;image.data[i]=output[0];image.data[i+1]=output[1];image.data[i+2]=output[2]; if(els.dither.checked && colors.length){const error=[input[0]-output[0],input[1]-output[1],input[2]-output[2]];spreadError(working,i+4,error,7/16);spreadError(working,i+(pixels-1)*4,error,3/16);spreadError(working,i+pixels*4,error,5/16);spreadError(working,i+(pixels+1)*4,error,1/16);}}} sctx.putImageData(image,0,0); ctx.drawImage(small,0,0,512,512); if(els.grid.checked && pixels<=64){ctx.strokeStyle='rgba(45,27,69,.24)';ctx.lineWidth=1; const step=512/pixels;for(let i=0;i<=pixels;i++){ctx.beginPath();ctx.moveTo(i*step,0);ctx.lineTo(i*step,512);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*step);ctx.lineTo(512,i*step);ctx.stroke();}} els.empty.hidden=true; els.download.disabled=false; }
function loadFile(file) { if(!file || !file.type.startsWith('image/')) return; const url=URL.createObjectURL(file); const image=new Image(); image.onload=()=>{sourceBitmap=image;sourceName=file.name;els.source.src=url;els.source.hidden=false;els.fileName.textContent=file.name.toUpperCase();els.clear.disabled=false;render();}; image.src=url; }
function clearSource(){ sourceBitmap=null;els.source.hidden=true;els.source.removeAttribute('src');els.file.value='';els.fileName.textContent='NO IMAGE SELECTED';els.clear.disabled=true;els.download.disabled=true;els.empty.hidden=false;els.canvas.getContext('2d').clearRect(0,0,els.canvas.width,els.canvas.height); }
function createAutoPalette() { if (!sourceBitmap) { els.paletteNote.textContent='UPLOAD AN IMAGE FIRST.'; return; } const sample=document.createElement('canvas'), ctx=sample.getContext('2d',{willReadFrequently:true}); sample.width=sample.height=96; ctx.drawImage(sourceBitmap,0,0,96,96); const data=ctx.getImageData(0,0,96,96).data, buckets=new Map(); for(let i=0;i<data.length;i+=4){if(data[i+3]<180)continue; const r=Math.round(data[i]/32)*32,g=Math.round(data[i+1]/32)*32,b=Math.round(data[i+2]/32)*32,key=`${r},${g},${b}`; buckets.set(key,(buckets.get(key)||0)+1); } const colors=[...buckets.entries()].sort((a,b)=>b[1]-a[1]).slice(0,+els.colorCount.value).map(([key])=>hexFromRgb(key.split(',').map(Number))); if(!colors.length){els.paletteNote.textContent='NO OPAQUE COLORS FOUND.';return;} activePreset=-1;els.palette.value=colors.join(', ');els.paletteNote.textContent=`FOUND ${colors.length} COLORS FROM YOUR IMAGE.`;drawPresetButtons();render(); }
els.choose.onclick=()=>els.file.click();els.file.onchange=e=>loadFile(e.target.files[0]);els.clear.onclick=clearSource;
['dragenter','dragover'].forEach(event=>els.drop.addEventListener(event,e=>{e.preventDefault();els.drop.classList.add('dragging')}));['dragleave','drop'].forEach(event=>els.drop.addEventListener(event,e=>{e.preventDefault();els.drop.classList.remove('dragging')}));els.drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));els.drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();els.file.click();}});
[els.pixel,els.gray,els.brightness,els.contrast,els.saturation,els.grid,els.compare,els.zoom,els.dither].forEach(control=>control.addEventListener('input',render));document.querySelectorAll('.pixel-presets button').forEach(button=>button.addEventListener('click',()=>{els.pixel.value=button.dataset.size;render();}));els.apply.onclick=()=>{activePreset=-1;drawPresetButtons();render();};els.palette.addEventListener('change',()=>{activePreset=-1;drawPresetButtons();render();});els.paletteMore.onclick=()=>{const open=els.paletteMorePanel.hidden;els.paletteMorePanel.hidden=!open;els.paletteMore.setAttribute('aria-expanded',String(open));els.paletteMore.querySelector('span').textContent=open?'−':'+';};els.autoPalette.onclick=createAutoPalette;
document.querySelectorAll('input[name=background]').forEach(el=>el.addEventListener('change',render));els.reset.onclick=()=>{els.pixel.value=16;els.palette.value=presets[1].colors.join(', ');activePreset=1;els.gray.checked=false;els.brightness.value=0;els.contrast.value=0;els.saturation.value=0;els.dither.checked=false;els.grid.checked=true;els.compare.checked=false;els.zoom.value=1;els.paletteMorePanel.hidden=true;els.paletteMore.setAttribute('aria-expanded','false');els.paletteMore.querySelector('span').textContent='+';els.paletteNote.textContent='AUTO PALETTE FINDS THE MOST COMMON IMAGE COLORS.';document.querySelector('[name=background][value=transparent]').checked=true;drawPresetButtons();render();};
els.download.onclick=()=>{if(!sourceBitmap)return; const scale=+els.scale.value, final=document.createElement('canvas'),ctx=final.getContext('2d');final.width=final.height=512*scale;if(document.querySelector('[name=background]:checked').value==='cream'){ctx.fillStyle='#f8f0dd';ctx.fillRect(0,0,final.width,final.height);}ctx.imageSmoothingEnabled=false;ctx.drawImage(els.canvas,0,0,final.width,final.height);const a=document.createElement('a');a.download=(sourceName.replace(/\.[^.]+$/,'')||'pixel-art')+'-pixel.png';a.href=final.toDataURL('image/png');a.click();};
drawPresetButtons();updateLabels();
